# Generated by Django 4.1.2 on 2022-10-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='caption',
            field=models.TextField(default='oops... look like there is not caption for this image'),
            preserve_default=False,
        ),
    ]
